name: Build, test and publish

on:
  push:

jobs:
  build-test-and-publish:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        java-package: jdk
        distribution: corretto

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-read-only: false

    - name: Build
      run: |
        cd application
        ./gradlew build

    - name: Save test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: |
          **/build/reports
          **/build/test-results

    - name: get container logs
      run: ./.github/workflows/print-container-logs.sh
      if: ${{ always() }}

    - name: Save container logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: container-logs
        path: ~/container-logs

    - name: Install gradle
      run: |
        curl -sSL https://services.gradle.org/distributions/gradle-8.5.3-bin.zip -o gradle-8.5.3-bin.zip
        unzip -q gradle-8.5.3-bin.zip -d /opt/gradle
        sudo ln -s /opt/gradle/gradle-8.5.3/bin/gradle /usr/local/bin/gradle

    - name: Install kind and kubectl
      run: |
        curl -sLo ./kind https://kind.sigs.k8s.io/dl/v0.16.0/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind
        curl -LO "https://dl.k8s.io/release/1.25.3/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Create kind cluster
      run: |
        ./application/manage/create-kind-cluster.sh
        ./test/test-kind-cluster.sh
        ./application/manage/delete-kind-cluster.sh
      
